name: Build Micro Virtual Runtime AT89S52
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install SDCC Compiler
              run: |
                sudo apt-get update
                sudo apt-get install -y sdcc

            - name: Run Build Script
              run: |
                chmod +x ./build.sh
                ./buid.sh buildsave

            - name: Save Compiled Binary
              uses: actions/upload-artifact@v4
              with: 
                name: compiled-microvr-build
                path: |
                  build/
                  !build/**/*.asm
                  !build/**/*.rel
                  !build/**/*.lk
                  !build/**/*.lst
                  !build/**/*.sym
                  !build/**/*.rst
                  !build/**/*.map
                  !build/**/*.mem
                
